spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #数据库索引
    database: 5
    #连接超时时间
    timeout: 5000
    lettuce:
      shutdown-timeout: 5000
      pool:
        #最小空闲
        min-idle: 0
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最大连接数
        max-active: 8